# Log Configurations
# log:
#   level: info
#   forceColor: false
#   disableColor: false

# Alert Configurations
# alert:
#   customTags: [testnet,dev]
#   dingtalk:
#     enabled: false
#     webhook: https://oapi.dingtalk.com/robot/send?access_token=${your_access_token}
#     secret:  ${your_access_secret}
#     atMobiles: []
#     isAtAll: false

# Blockchain Monitoring Configurations
# blockchain:
#   nodes:
#     node0: http://ip0:8545
#     node1: http://ip1:8545
#     node2: http://ip2:8545
#   interval: 5s
#   availabilityReport:
#     threshold: 1m
#     reminder: 5m
#   nodeHeightReport:
#     ErrorTolerantReportConfig:
#       threshold: 1m
#       reminder: 5m
#     maxGap: 30
#   blockchainHeightReport:
#     threshold: 1m
#     reminder: 5m
