# Log Configurations
# log:
#   level: info
#   forceColor: false
#   disableColor: false
#   alertHook: # Alert hooking settings
#     # Hooked logrus levels for alert notification
#     levels: [warn,error,fatal]
#     # Default notification channels
#     channels: []

# Alert Configurations
# alert:
#   # Custom tags are usually used to differentiate between different networks and enviroments
#   # such as mainnet/testnet, prod/test/dev or any custom info for more details.
#   customTags: [dev,test]
#   # Channels: Notification channels
#   # Key: Unique identifier for the channel (e.g., channel ID)
#   # Value: Configuration for the channel
#   channels:
#     dingrobot: # Example channel configuration for DingTalk
#       platform: dingtalk # Mandatory field indicating the channel type
#       webhook: https://oapi.dingtalk.com/robot/send?access_token=${your_access_token}
#       secret:  ${your_access_secret}
#       atMobiles: []
#       isAtAll: false
#     tgrobot: # Example channel configuration for Telegram
#       platform: telegram # Mandatory field indicating the channel type
#       apiToken:  ${your_api_token}
#       chatId: ${your_chat_id}

# Blockchain Monitoring Configurations
# blockchain:
#   nodes:
#     node0: http://ip0:8545
#     node1: http://ip1:8545
#     node2: http://ip2:8545
#   interval: 5s
#   availabilityReport:
#     threshold: 1m
#     reminder: 5m
#   nodeHeightReport:
#     ErrorTolerantReportConfig:
#       threshold: 1m
#       reminder: 5m
#     maxGap: 30
#   blockchainHeightReport:
#     threshold: 1m
#     reminder: 5m
